Test
9320test/test pull request #1
Opened 2022-05-14 12:16 UTC by mizuna-git

初めてのプルリクエスト

2022-05-14 12:26 UTC, 9320test commented
良い感じです！

2022-05-14 12:43 UTC, 9320test requested changes
コメントを確認してください。

2022-05-14 12:43 UTC, 9320test commented on a.txt
> +
ここは4行目です

2022-05-14 12:43 UTC, 9320test commented on a.txt
> +second
ここは2行目

2022-05-14 12:55 UTC, mizuna-git commented
再度プッシュしたので、確認お願いします！

2022-05-14 13:04 UTC, 9320test commented on a.txt
> -・test branchの作成
あああ

2022-05-14 13:08 UTC, 9320test commented on a.txt
> -・test branchの作成
よいと思います

2022-05-14 13:08 UTC, 9320test approved these changes

2022-05-14 13:09 UTC, 9320test commented
👍 
😄

2022-05-15 04:13 UTC, mizuna-git commented
aaa

2022-05-15 04:14 UTC, mizuna-git reviewed
ok

2022-05-15 04:16 UTC, merged